config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'static_pages#main_page'

  resources :tweets

  resources :profiles

  resources :relationships, only: [:create]

  get 'h/:hash_tag_id', to: 'hashtags#show', as: :hash_tag

end

app/models/hashtag.rb
class Hashtag < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  mount_uploader :pic, PicUploader
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
	include Twitter::Extractor

	def extract_hash_tags
		extract_hashtags(self.tweet)
	end

	validate :hashtags_created

	def hashtags_created

		begin
			transaction do

				@hashtags = self.extract_hash_tags

				@hashtags.each do |the_hashtag|
					if Hashtag.where(h: the_hashtag).any?
						#do nothing
					else
						if Hashtag.create!(h: the_hashtag)
						#do nothing
						else
							self.errors.add(:tweet, "The hashtag is invalid")
						end
					end
				end
			end
		rescue
			#code will continue here if runtime error is encountered
			self.errors.add(:tweet, "The hashtag(s) are invalid.")
		end

	end


	belongs_to :user
	validates :tweet, length: { maximum: 140}
	#has_and_belongs_to_many :hashtags
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tweets

  has_one :profile

  has_many :active_relationships, class_name:  "Relationship",
                                 foreign_key: "follower_id",
                                 dependent:   :destroy

  has_many :passive_relationships, class_name:  "Relationship",
	                   foreign_key: "followed_id",
	                   dependent:   :destroy

has_many :following, through: :active_relationships, source: :followed

has_many :followers, through: :passive_relationships, source: :follower

 def follow(other_user)
   active_relationships.create(followed_id: other_user.id)
 end

 # Unfollows a user.
 def unfollow(other_user)
   active_relationships.find_by(followed_id: other_user.id).destroy
 end

 # Returns true if the current user is following the other user.
 def following?(other_user)
   following.include?(other_user)
 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
	def show
		#@hashtag = Hashtagfind(params[:id])
		@hashtag = Hashtag.where(h: params[:hash_tag_id]).first
		@tweets = Tweet.all
		if @hashtag

			@filtered_tweets = @tweets.select {|t| t.extract_hash_tags.include?(@hashtag.h)}
		else
			@filtered_tweets = Array.new
			flash.now[:notice] = "There are no tweets with #{params[:hash_tag_id]}"
		end
	end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	def new
		if current_user.profile
			redirect_to profile_path(current_user.profile)
		else

		@profile = Profile.new
	end

	end

	def create

		@profile = Profile.new(profile_params)
		@profile.user = current_user

		if @profile.save
			flash[:success] = "Profile succesfully created"

		else
			flash.now[:danger] = "Please fix the errros below"
			render 'new'

		end
		redirect_to profile_path(current_user.profile)
	end

	def show
		@profile = Profile.find(params[:id])
	end

	def profile_params

		params.require(:profile).permit(:description, :pic)
	end


end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	def create
		#@realtionship = Realtionship.new(realtionship_params)
		#@realtionship.follower_id = current_user
		@user = User.find(relationship_params[:followed_id])

		if current_user.follow(@user)
			flash[:success] = "You are now following #{@user.email}"
		else
			flash[:danger] = "The user cannot be followed at this time"
		end
		redirect_to tweets_path
	end

	def relationship_params
		params.require(:relationship).permit(:followed_id)
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def main_page
	end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

	before_action :authenticate_user!

	def new
		@tweet = Tweet.new
		@tweets = current_user.tweets
	end

	def create
		@tweet = Tweet.new(tweet_params)
		@tweet.user = current_user
		if @tweet.save
			flash[:success] = "You have created a tweet"
		
		#@tweet = Tweet.create(tweet_params)
		else 
			flash[:danger] = "Please fix the problems below"

		end
		@tweets = current_user.tweets
		render 'new'

	end

	def index
		@tweets = Tweet.all.reject{|tweet| tweet.user == current_user}
		@relationship = Relationship.new 
	end

	private

	def tweet_params
		params.require(:tweet).permit(:tweet)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/realtionships_helper.rb
module RealtionshipsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/hashtags/show.html.erb
<ul>
	<% @filtered_tweets.each do |t| %>
	<li> <%= t.tweet %> </li> <br>
	<%end%>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twipper</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body style = "background: url(/assets/background_twipper.png);">
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
        <%= link_to "Twipper", root_path %>
      </div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <% if !user_signed_in? %>

        <li>
        <%= link_to "Sign Up", new_user_registration_path %>
        </li>

        <li>
        <%= link_to "Sign In", new_user_session_path %>
        </li>


        <%else%>

          <li>
          <%= link_to "My Profile", new_profile_path %>
          </li>

          <li>
          <%= link_to "New Tweet", new_tweet_path %>
          </li>

          <li>
            <%= link_to "News Feed", tweets_path %>
          </li>
        <% end %>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
    
        </li>

        <% if user_signed_in? %> 
           <li>
        <%= link_to "Log out", destroy_user_session_path, method: :delete %>
          </li>
        <% end %>
 
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% flash.each do |key, value| %>
<div class="alert alert-<%= key %>"> <%= value %> </div>
<% end %>

<%= yield %>

</body>
</html>

app/views/profiles/new.html.erb
New Profile Form

<%= simple_form_for @profile do |f| %>
	<%=f.input :description %>
	<%=f.input :pic %>
	<%=f.button :submit %>

<% end %>

app/views/profiles/show.html.erb
This is the profile for <%= @profile.user.email %>
<%= image_tag @profile.pic %>

app/views/static_pages/main_page.html.erb
<div class = "container">
<div class="jumbotron" style="opacity :0.8; width: 750px; margin-left: auto; margin-right: auto;">
  <h1>Welcome to Twipper!</h1>
  <p>It's like twitter but not really</p>
  <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
</div>
</div>

app/views/tweets/index.html.erb
Timeline
<ul>
<% @tweets.each do |tweet| %>
	<li> <%= tweet.user.email %> || <%= tweet.tweet %> 
	<% if current_user.following?(tweet.user) %>
	<button type="button" class="btn btn-danger">
		Already following
	</button>
	<%else %>
	<%= simple_form_for @relationship do |f| %>
	<%= f.input :followed_id, as: :hidden, input_html: {value: tweet.user.id } %>
	<%= f.button :submit, class: 'btn btn-primary' %>
	<% end %>
	<% end %>
	</li>
	<br>
	<% end %>
</ul>

app/views/tweets/new.html.erb
<%= simple_form_for @tweet do |f| %>
  <%= f.input :tweet %>
  <%= f.button :submit %>
<% end %>

<br>

Here are all my tweets: <br><br>

<ul>
<% @tweets.each do |tweet| %>
	<li><%= tweet.tweet %></li>
<% end %>

<ul>